# Google Cloud Build configuration for automated deployment
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/limpiapp-backend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/limpiapp-backend:latest'
      - '.'
    dir: 'backend'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/limpiapp-backend:$SHORT_SHA'

  # Step 3: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/limpiapp-backend:latest'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'limpiapp-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/limpiapp-backend:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--port'
      - '3000'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=3000'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,JWT_SECRET=JWT_SECRET:latest,STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest'

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/limpiapp-backend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/limpiapp-backend:latest'

# Substitution variables with default values
substitutions:
  _REGION: 'us-central1'
  _MEMORY: '512Mi'
  _CPU: '1'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'

# Timeout for the entire build
timeout: '1200s'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
